name: Deploy Backend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug secrets
        run: |
          echo "DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME:0:3}***"
          echo "DOCKERHUB_TOKEN length: ${#DOCKERHUB_TOKEN}"
          echo "DOCKERHUB_TOKEN first 4 chars: ${DOCKERHUB_TOKEN:0:4}***"
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/basicdeploy-backend:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/basicdeploy-backend:latest
            